### ISSUE TITLE
Having trouble setting up test using KVSInlineCredentialsHandler( ) error botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch)

### ISSUE THREAD

**Issue by dcoder4** [Neosperience/backpack#1]
Hi great project! I'm trying to test the KVS Skyline code just using the KVSInlineCredentialsHandler(), but getting a Boto3 error. Its as though it is not setting the  aws_access_key_id and aws_secret_access_key in the session properly in line #165  of https://github.com/Neosperience/backpack/blob/master/backpack/kvs.py.

Am I creating calling the credentials function correctly?

Here is a snippit:

`     credentials_handler = KVSInlineCredentialsHandler(aws_access_key_id="XXXXXXXXXX", aws_secret_access_key="XXXXXXXXXX")
        self.skyline = KVSSkyLine(
            stream_region=stream_region,
            stream_name=stream_name,
            credentials_handler=credentials_handler,
            dotenv_path=DOTENV_PATH
        )
        # This call opens the streaming pipeline:
        self.skyline.start_streaming()`

It fails on line #172. I assume its skipping the setting of aws_access_key_id and aws_secret_access_key in the IF statement line #165. If checked/recreated my Access Keys a couple of times (and also ensured the key has no special characters).
Error returned is:
`
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetCallerIdentity operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
` 
Error trace is:
`
Traceback (most recent call last):
  File "/panorama/app.py", line 155, in main
    app = Application()
  File "/panorama/app.py", line 31, in __init__
    aws_secret_access_key="XXXXXXXXX"
  File "/usr/local/lib/python3.7/dist-packages/backpack/kvs.py", line 275, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/backpack/kvs.py", line 173, in __init__
    self.caller_arn = self.session.client('sts').get_caller_identity()['Arn']
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
`
Any idea what I am doing wrong? Thanks.

**Comment by dcoder4** [comment]
Found issue! There is an error on line #168 of 'https://github.com/Neosperience/backpack/blob/master/backpack/kvs.py'

Code is:
`self.session = boto3.Session(
                aws_access_key_id=aws_access_key_id,
                aws_secret_access_key=aws_access_key_id
            )`
and should be:
`self.session = boto3.Session(
                aws_access_key_id=aws_access_key_id,
                aws_secret_access_key=aws_secret_access_key
            )`

**Comment by mrtj** [comment]
Thank you for the bugfixing and the contribution!
